metadata:
  complexity: Medium
  id: 297
  name: Exhaust Node Resources
  platform: kubernetes

spec:
  environment:
    applications:
      otel_demo:
        enabled: true
    tools:
      category: sre
      selected:
        - prometheus
        - grafana
        - jaeger
        - chaos-mesh

  faults:
    - custom:
        name: exhaust-node-resources
        exhaust_node_resources:
          workload:
            kind: Deployment
            name: cart
            namespace: "{{ applications_helm_releases.otel_demo.namespace }}"
