---
fault:
  - entity:
      name: cart
      group_id: cart
      kind: Deployment
    type: custom
    name: exhaust-node-resources
    condition: Node resource exhaustion
    category: Change
    fault_mechanism: exhaust-node-resources

alerts:
  - id: CPUSpend
    group_id: cart
    metadata:
      description: Cart pod CPU usage is high due to StressChaos injection
  - id: RequestLatency
    group_id: cart
    metadata:
      description: Latency of cart deployment increases due to CPU resource contention

groups:
  - id: cart
    kind: Deployment
    namespace: otel-demo
    filter:
      - cart.*
    root_cause: true

aliases:
  - - cart

propagations: []

recommended_actions:
  - solution:
      id: tune_resources
      actions:
        - Increase CPU/memory requests for cart deployment
        - Use autoscaling or reduce workload concurrency
