---
fault:
  - entity:
      name: cart
      group_id: cart
      kind: Deployment
    type: custom
    name: exhaust-node-resources
    condition: Node resource exhaustion
    category: Change
    fault_mechanism: exhaust-node-resources

alerts:
  - id: CPUSpend
    group_id: cluster-node-1
    metadata:
      description: Node CPU usage is high due to resource exhaustion
  - id: RequestLatency
    group_id: cart
    metadata:
      description: Latency of cart deployment increases due to CPU resource contention

groups:
  - id: cart
    kind: Deployment
    namespace: otel-demo
    filter:
      - cart.*
    root_cause: true
  - id: cluster-node-1
    kind: Node
    namespace: kube-system
    filter:
      - .*

aliases:
  - - cart
    - cluster-node-1

propagations:
  - source: cluster-node-1
    target: cart
    condition: Node resource pressure prevents new pods from being scheduled
    effect: Cart deployment pods remain pending and requests may fail

recommended_actions:
  - solution:
      id: rebalance_or_scale
      actions:
        - Rebalance workloads to another node
        - Scale up cluster node capacity