---
- name: Create VPC for kOps clusters
  amazon.aws.ec2_vpc_net:
    name: "{{ awx_stack.name_prefix }}-vpc"
    cidr_block: "{{ awx_stack.runners.aws.vpc.cidr }}"
    region: "{{ awx_cluster.aws.region }}"
    state: present
  register: awx_vpc_info

- name: Create an Internet Gateway associated with VPC
  amazon.aws.ec2_vpc_igw:
    vpc_id: "{{ awx_vpc_info.vpc.id }}"
    region: "{{ awx_cluster.aws.region }}"
    state: present
  register: awx_igw_info

- name: Create a subnet for each cluster
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ awx_vpc_info.vpc.id }}"
    cidr: "{{ awx_stack.runners.aws.subnet.public_base }}.{{ item * 2 }}.0/23"
    az: "{{ awx_cluster.aws.zones[0] }}"
    region: "{{ awx_cluster.aws.region }}"
    map_public: true
    state: present
    tags:
      Name: "{{ awx_stack.name_prefix }}-public-subnet-{{ item }}"
      Environment: k8s
      ManagedBy: ansible
  loop: "{{ range(1, (awx_cluster_names | length) + 1) }}"
  register: awx_public_subnets

- name: Parse subnet ids
  ansible.builtin.set_fact:
    awx_subnet_ids: "{{ awx_public_subnets.results | community.general.json_query('[*].subnet.id') }}"

- name: Create a route table for public subnets
  amazon.aws.ec2_vpc_route_table:
    vpc_id: "{{ awx_vpc_info.vpc.id }}"
    region: "{{ awx_cluster.aws.region }}"
    subnets: "{{ awx_subnet_ids }}"
    routes:
      - dest: "0.0.0.0/0"
        gateway_id: "{{ awx_igw_info.gateway_id }}"
    tags:
      Name: "{{ awx_stack.name_prefix }}-public-route-table"
      Creator: "ansible"
    state: present

- name: Asynchronously create kOps clusters
  ansible.builtin.command:
    argv:
      - kops
      - create
      - cluster
      - "{{ item[0] }}"
      - --cloud
      - aws
      - --topology
      - public
      - --network-id
      - "{{ awx_vpc_info.vpc.id }}"
      - --subnets
      - "{{ item[1] }}"
      - --zones
      - "{{ awx_cluster.aws.zones | join(',') }}"
      - --ssh-public-key
      - "{{ awx_cluster.ssh.public_key_path }}"
      - --control-plane-size
      - "{{ awx_cluster.nodes.control.instance_type }}"
      - --control-plane-count
      - "{{ awx_cluster.nodes.control.count }}"
      - --node-size
      - "{{ awx_cluster.nodes.worker.instance_type }}"
      - --node-count
      - "{{ awx_cluster.nodes.worker.count }}"
      - --networking
      - "{{ awx_cluster.networking.mode }}"
      - --state
      - "{{ awx_kops_state_store }}"
  async: 600
  loop: "{{ awx_cluster_names | zip(awx_subnet_ids) }}"
  poll: 0
  register: awx_async_create_results

- name: Wait for asynchronous operations to complete
  ansible.builtin.async_status:
    jid: "{{ item.ansible_job_id }}"
  loop: "{{ awx_async_create_results.results }}"
  register: awx_async_create_poll_results
  until: awx_async_create_poll_results.finished
  delay: 30
  retries: 20

- name: Clean up ansychronous operations
  ansible.builtin.async_status:
    mode: cleanup
    jid: "{{ item.ansible_job_id }}"
  loop: "{{ awx_async_create_results.results }}"

- name: Asynchronously build kOps clusters
  ansible.builtin.command:
    argv:
      - kops
      - update
      - cluster
      - --name
      - "{{ item }}"
      - --state
      - "{{ awx_kops_state_store }}"
      - --yes
      - --internal
      - --create-kube-config=false
  async: 600
  loop: "{{ awx_cluster_names }}"
  poll: 0
  register: awx_async_update_results

- name: Wait for asynchronous operations to complete
  ansible.builtin.async_status:
    jid: "{{ item.ansible_job_id }}"
  loop: "{{ awx_async_update_results.results }}"
  register: awx_async_update_poll_results
  until: awx_async_update_poll_results.finished
  delay: 30
  retries: 20

- name: Clean up ansychronous operations
  ansible.builtin.async_status:
    mode: cleanup
    jid: "{{ item.ansible_job_id }}"
  loop: "{{ awx_async_update_results.results }}"

- name: Export the kubeconfigs for the clusters
  ansible.builtin.command:
    argv:
      - kops
      - export
      - --name
      - "{{ item }}"
      - kubecfg
      - --admin
      - --state
      - "{{ awx_kops_state_store }}"
      - --kubeconfig
      - /tmp/{{ item }}.yaml
  loop: "{{ awx_cluster_names }}"
  register: awx_kops_export_output
  changed_when: awx_kops_export_output.rc == 0

- name: Asynchronously validate kOps cluster
  ansible.builtin.command:
    argv:
      - kops
      - validate
      - cluster
      - --state
      - "{{ awx_kops_state_store }}"
      - --wait
      - 10m
  environment:
    KUBECONFIG: /tmp/{{ item }}.yaml
  async: 600
  loop: "{{ awx_cluster_names }}"
  poll: 0
  register: awx_async_validate_results

- name: Wait for asynchronous operations to complete
  ansible.builtin.async_status:
    jid: "{{ item.ansible_job_id }}"
  loop: "{{ awx_async_validate_results.results }}"
  register: awx_async_validate_poll_results
  until: awx_async_validate_poll_results.finished
  delay: 60
  retries: 10

- name: Clean up ansychronous operations
  ansible.builtin.async_status:
    mode: cleanup
    jid: "{{ item.ansible_job_id }}"
  loop: "{{ awx_async_validate_results.results }}"
