---
- name: Import variable setting tasks
  ansible.builtin.import_tasks:
    file: set_faults_workload_container_index.yaml
  vars:
    faults_workload: "{{ spec.workload }}"

- name: Inject CPU and Memory stress using Chaos Mesh
  kubernetes.core.k8s:
    kubeconfig: "{{ faults_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: chaos-mesh.org/v1alpha1
      kind: StressChaos
      metadata:
        name: stress-chaos-{{ spec.workload.name }}
        namespace: "{{ spec.workload.namespace }}"
      spec:
        mode: one
        selector:
          namespaces:
            - "{{ spec.workload.namespace }}"
          labelSelectors:
            app.kubernetes.io/name: "{{ spec.workload.name }}"
        stressors:
          cpu:
            workers: 4
          memory:
            workers: 1
            size: "256MB"
        duration: "60s"
        scheduler:
          cron: "@once"

- name: Confirm stress chaos created
  kubernetes.core.k8s_info:
    kubeconfig: "{{ faults_cluster.kubeconfig }}"
    api_version: chaos-mesh.org/v1alpha1
    kind: StressChaos
    namespace: "{{ spec.workload.namespace }}"
    name: "stress-chaos-{{ spec.workload.name }}"
  register: stress_chaos_info

- name: Import workload restart tasks
  ansible.builtin.import_tasks:
    file: force_workload_restart.yaml
  when:
    - (spec.workload.restart_policy | default('force')) == 'force'
  vars:
    faults_workload: "{{ spec.workload }}"
