---
- name: Get nodes labeled as target for resource hog
  kubernetes.core.k8s_info:
    kubeconfig: "{{ faults_cluster.kubeconfig }}"
    kind: Node
    label_selectors:
      - node-role.kubernetes.io/app=true
  register: node_list

- name: Select the node labeled for this fault
  set_fact:
    target_node: "{{ (node_list.resources | list)[0].metadata.name }}"
  when: node_list.resources | list | length > 0

- name: Remove node label from target node
  kubernetes.core.k8s:
    kubeconfig: "{{ faults_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: v1
      kind: Node
      metadata:
        name: "{{ target_node }}"
        labels:
          node-role.kubernetes.io/app: null
    state: present
  when: target_node is defined
