---
- name: Retrieve StressChaos objects for target workload
  kubernetes.core.k8s_info:
    kubeconfig: "{{ faults_cluster.kubeconfig }}"
    api_version: chaos-mesh.org/v1alpha1
    kind: StressChaos
    namespace: "{{ spec.workload.namespace }}"
    label_selectors:
      - app.kubernetes.io/name={{ spec.workload.name }}
  register: stress_chaos_list

- name: Remove StressChaos CRs related to this workload
  kubernetes.core.k8s:
    kubeconfig: "{{ faults_cluster.kubeconfig }}"
    state: absent
    api_version: chaos-mesh.org/v1alpha1
    kind: StressChaos
    name: "{{ item.metadata.name }}"
    namespace: "{{ spec.workload.namespace }}"
  loop: "{{ stress_chaos_list.resources }}"
  when: stress_chaos_list.resources | length > 0

- name: Confirm StressChaos removal
  kubernetes.core.k8s_info:
    kubeconfig: "{{ faults_cluster.kubeconfig }}"
    api_version: chaos-mesh.org/v1alpha1
    kind: StressChaos
    namespace: "{{ spec.workload.namespace }}"
  register: stress_chaos_post_delete
